[package]
name = "typ"
version = "0.1.0"
authors = ["Yuuki Rika"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.iced]
version = "0.4"
features = ["default_system_font"]
