[package]
name = "typ"
version = "0.1.0"
authors = ["Yuuki Rika"]
license = "MIT OR Apache-2.0"
edition = "2021"

# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.iced]
version = "0.4"
features = ["default_system_font"]
