name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          check-latest: true
      - run: corepack prepare yarn@4 --activate

      - run: yarn install
      - run: yarn tauri build
